version: '3.8'

services:
    web:
        image: nginx:latest
        container_name: web
        volumes:
            - ./cert/certbot/conf:/etc/letsencrypt
            - ./cert/certbot/www:/var/www/certbot
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - '80:80'

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./cert/certbot/conf:/etc/letsencrypt
            - ./cert/certbot/www:/var/www/certbot
