# Generated by Django 5.2.1 on 2025-08-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('category1', models.CharField(max_length=50)),
                ('category2', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('road_address', models.CharField(max_length=200)),
                ('lot_address', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
        ),
    ]
