# Generated by Django 5.2.5 on 2025-08-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
