# Generated by Django 5.2.4 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
