# Generated by Django 5.2.1 on 2025-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fcm_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCurrentInfo',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('uv_index', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weather_condition', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherFutureInfo',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('uv_index', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weather_condition', models.CharField(max_length=50)),
                ('time_set', models.DateTimeField()),
            ],
        ),
    ]
