# Generated by Django 5.2.5 on 2025-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_alertlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertlog',
            old_name='message',
            new_name='alert_message',
        ),
        migrations.RemoveField(
            model_name='alertlog',
            name='id',
        ),
        migrations.AddField(
            model_name='alertlog',
            name='alert_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='alert_type',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertlog',
            name='location_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
