# Generated by Django 5.2.5 on 2025-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_rename_message_alertlog_alert_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='alert_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='location_name',
            field=models.CharField(default='동대문구', max_length=100),
        ),
        migrations.AlterField(
            model_name='weathercurrentinfo',
            name='location_name',
            field=models.CharField(default='동대문구', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherfutureinfo',
            name='location_name',
            field=models.CharField(default='동대문구', max_length=100),
        ),
    ]
