# Generated by Django 5.2.5 on 2025-08-20 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0004_alter_alertlog_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherfutureinfo',
            name='time_set',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
