# Generated by Django 5.2.4 on 2025-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMapTraffic',
            fields=[
                ('traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=100)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
            ],
            options={
                'db_table': 'live_map_traffic',
            },
        ),
        migrations.CreateModel(
            name='TrafficCurrentInfo',
            fields=[
                ('traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=100)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_current_info',
            },
        ),
        migrations.CreateModel(
            name='TrafficFutureInfo',
            fields=[
                ('traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=100)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('source_id', models.IntegerField()),
                ('time_set', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_future_info',
            },
        ),
    ]
