# Generated by Django 5.2.5 on 2025-08-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMapTraffic',
            fields=[
                ('traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(default='unknown', max_length=100)),
                ('start_node', models.CharField(default='unknown', max_length=100)),
                ('end_node', models.CharField(default='unknown', max_length=100)),
                ('congestion', models.IntegerField(default=0)),
                ('speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('road_type', models.CharField(blank=True, max_length=10, null=True)),
                ('coordinates', models.JSONField(default=list)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'live_map_traffic',
            },
        ),
        migrations.CreateModel(
            name='TrafficCurrentInfo',
            fields=[
                ('traffic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Traffic.livemaptraffic')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_current_info',
            },
        ),
        migrations.CreateModel(
            name='TrafficFutureInfo',
            fields=[
                ('traffic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Traffic.livemaptraffic')),
                ('predicted_congestion', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('time_set', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_future_info',
            },
        ),
    ]
