# Generated by Django 5.2.5 on 2025-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livemaptraffic',
            name='end_node',
        ),
        migrations.RemoveField(
            model_name='livemaptraffic',
            name='road_name',
        ),
        migrations.RemoveField(
            model_name='livemaptraffic',
            name='road_type',
        ),
        migrations.RemoveField(
            model_name='livemaptraffic',
            name='start_node',
        ),
        migrations.RemoveField(
            model_name='livemaptraffic',
            name='update_time',
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='accidentDetailCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='accidentDetailName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='accidentUpperCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='accidentUpperName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='endNodeName',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='isAccidentNode',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='roadType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='startNodeName',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='livemaptraffic',
            name='updateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='accidentDetailCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='accidentDetailName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='accidentUpperCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='accidentUpperName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='congestion',
            field=models.IntegerField(choices=[(0, '정보없음'), (1, '원활'), (2, '서행'), (3, '지체'), (4, '정체')], default=0),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='isAccidentNode',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='livemaptraffic',
            name='congestion',
            field=models.IntegerField(choices=[(0, '정보없음'), (1, '원활'), (2, '서행'), (3, '지체'), (4, '정체')], default=0),
        ),
    ]
