# Generated by Django 5.2.5 on 2025-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traffic', '0002_remove_livemaptraffic_end_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficcurrentinfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='trafficcurrentinfo',
            name='longitude',
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='coordinate',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trafficcurrentinfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
